### ISSUE TITLE
Java error on generate-dtd command line

### ISSUE THREAD

**Issue by Nico-Amplexor** [oasis-open/dita-rng-converter#23]
Hello,

I setup converter environment using One-Time Setup procedure.

I run following command line : 
ant generate-dtd -Drngsrc="C:/PROJETS/AAA - DITA-OT tests/dita-rng-converter-master/inputs/rng" "-Ddita-ot-dir=C:/PROJETS/AAA - DITA-OT tests/dita-rng-converter-master/dita-ot-3.7"

But I get following error : 
`Buildfile: C:\PROJETS\AAA - DITA-OT tests\dita-rng-converter-master\build.xml
     [echo] catalogOutDir=C:\PROJETS\AAA - DITA-OT tests\dita-rng-converter-master\build\1.3
     [echo] catalogPathUri="file:/C:/PROJETS/AAA%20-%20DITA-OT%20tests/dita-rng-converter-master/dita-ot-3.7/catalog-dita.xml"

init:
     [echo] outdir=C:\PROJETS\AAA - DITA-OT tests\dita-rng-converter-master\build
     [echo] catalogOutDir="C:\PROJETS\AAA - DITA-OT tests\dita-rng-converter-master\build\1.3"

clean:

generate-catalogs:

generate-dtd:

BUILD FAILED
C:\PROJETS\AAA - DITA-OT tests\dita-rng-converter-master\build.xml:232: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:429)
        at org.apache.tools.ant.types.Permissions.setSecurityManager(Permissions.java:103)
        at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:216)
        at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
        at org.apache.tools.ant.taskdefs.Java.run(Java.java:891)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 0 seconds`

My java installation : 
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)
Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

Thanks for your help.

Regards,
Nicolas

**Comment by Nico-Amplexor** [comment]
Hello,
I resolved this issue using Java 17.
